# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credit_predict.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63redit_predict.proto\x12\x0e\x63redit_predict\"\"\n\x0ePredictRequest\x12\x10\n\x08Requests\x18\x01 \x01(\t\"\x1d\n\nReplyArray\x12\x0f\n\x07returns\x18\x01 \x01(\t2T\n\tPredictor\x12G\n\x07Predict\x12\x1e.credit_predict.PredictRequest\x1a\x1a.credit_predict.ReplyArray\"\x00\x42<\n\x1eio.grpc.examples.credit_preditB\x12\x43reditPredictProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_PREDICTREQUEST = DESCRIPTOR.message_types_by_name['PredictRequest']
_REPLYARRAY = DESCRIPTOR.message_types_by_name['ReplyArray']
PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'credit_predict_pb2'
  # @@protoc_insertion_point(class_scope:credit_predict.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

ReplyArray = _reflection.GeneratedProtocolMessageType('ReplyArray', (_message.Message,), {
  'DESCRIPTOR' : _REPLYARRAY,
  '__module__' : 'credit_predict_pb2'
  # @@protoc_insertion_point(class_scope:credit_predict.ReplyArray)
  })
_sym_db.RegisterMessage(ReplyArray)

_PREDICTOR = DESCRIPTOR.services_by_name['Predictor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036io.grpc.examples.credit_preditB\022CreditPredictProtoP\001\242\002\003HLW'
  _PREDICTREQUEST._serialized_start=40
  _PREDICTREQUEST._serialized_end=74
  _REPLYARRAY._serialized_start=76
  _REPLYARRAY._serialized_end=105
  _PREDICTOR._serialized_start=107
  _PREDICTOR._serialized_end=191
# @@protoc_insertion_point(module_scope)
