apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: predictor
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: predictor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: predictor
    spec:
      containers:
        - image: asia.gcr.io/ds-final-gotcha/vincentliao11/predictor:5.0
          name: predictor
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
